name: "Update cachix cache"

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04-arm]
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: radxa
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: cachix watch-exec radxa ./build
